### ISSUE TITLE
Login Failed: Attempted to set 'phusr' cookie

### ISSUE THREAD

**Issue by shirish87** [relrod/phabricator-openshift-quickstart#1]
Following the steps mentioned in the readme, I set up an instance on OpenShift. 
However, after creating the admin account, I'm unable to log in. The following message is displayed.

Login failed:
Attempted to set 'phusr' cookie to 'test', but your browser did not accept the cookie.
Clear your cookies and try again.

Tried this in the latest versions of Chrome, FF and Opera. The cookie seems to be set correctly, but login still fails.

Screenshot:
http://i.imgur.com/Oq5fY.jpg

Thanks for this!

**Comment by shirish87** [comment]
Had missed replacing the value for 'metamta.domain' in myconfig.conf.php

**Comment by floatingLomas** [comment]
That wasn't my problem.  Mine was that it was running has HTTP instead of HTTPS.

I followed [this tip](https://openshift.redhat.com/community/kb/kb-e1044-how-to-redirect-traffic-to-https) and added an `.htaccess` file in the webroot folder which contained:

```
RewriteEngine on  

RewriteCond %{HTTP:X-Forwarded-Proto} !https  
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R,L]  
```

Now it works fine.
